# Generated by Django 3.0.2 on 2020-02-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdetection',
            name='satellite_scale',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
    ]
