# Generated by Django 3.0.2 on 2020-02-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_shipdetection_satellite_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipdetection',
            name='satellite_scale',
        ),
    ]
